---
- name: Reboot server
  hosts: "{{ target }}"
  remote_user: root
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: /app/private.pem
    ansible_ssh_port: 22
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Reboot the server
      reboot:
        reboot_timeout: 600
