---
- name: "Check for updates"
  hosts: "{{ target }}"
  remote_user: root
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: /app/private.pem
    ansible_ssh_port: 22
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Apt Update"
      ignore_errors: yes
      apt:
        update_cache: yes
    - name: "Check how many updates are required"
      shell: "/usr/lib/update-notifier/apt-check"
      register: output
    - debug: var=output.stderr
    - name: "Check if reboot is required"
      stat:
        path: /var/run/reboot-required
      register: reboot_file
    - name: "Show reboot required status"
      debug:
        var: reboot_file.stat.exists